### ISSUE TITLE
Initial Task List

### ISSUE THREAD

**Issue by brucebolick** [AdmiralPotato/react-video-hero#1]
**Objectives for February 18th, 2016**
- [ ]  Create a scaleable video that works on iOS, Android and Desktop that swaps out the actual video source based on the resolution of the device.
- [ ] Make the video loop seamlessly.
- [ ] Make the video hide itself or stop when it is not on screen.
- [ ] Overlay things on top of the video, so that we can have interactivity with the hero without accidentally pausing the video.
- [ ] Write documentation on how to consume it.
- [ ] Post a preliminary npm module for the react-video-hero
